.MODEL SMALL
.STACK 100H
.DATA 
    CR EQU 0DH
    LF EQU OAH
MSG1 DB 'ENTER THE UPPER CASE LETTER: $'
MSG2 DB 0DH,0AH,'THE LETTER IN LOWER CASE IS '
CHARU DB ?,'$'
MSG3 DB 0DH,0AH,'ENTER THE LOWER CASE LETTER: $'
MSG4 DB 0DH,0AH,'THE LETTER IN UPPER CASE IS '
CHARL DB ?,'$' 
.CODE
MAIN PROC 
    MOV AX,@DATA
    MOV DS,AX
    LEA DX,MSG1
    MOV AH,9
    INT 21H
    MOV AH,1
    INT 21H
    ADD AL,20H
    MOV CHARU,AL
    LEA DX,MSG2
    MOV AH,9
    INT 21H 
    
    LEA DX,MSG3
    MOV AH,9
    INT 21H
    MOV AH,1
    INT 21H
    SUB AL,20H
    MOV CHARL,AL
    LEA DX,MSG4
    MOV AH,9
    INT 21H
    MOV AH,4CH
    INT 21H
    MAIN ENDP
END MAIN